@Harini
@BloodIssueManagement
Feature: Harini_17/05/2026  Blood Issue Management

  Background:
    Given the user is on the login page
    When the user clicks Super Admin button
    And the user clicks the Sign in button
    Then the user should be redirected to super admin dashboard
    When the user clicks on the Blood Bank menu
    And the user clicks on Blood Issue Details
    Then the Blood Issue Details page should be displayed

  @IssueBloodValidDetails
  Scenario: Issue blood with valid details
    When the user clicks on Issue Blood button
    Then the Issue Blood popup should be displayed
    When the user enters valid blood issue details
    Then the blood group should be autogenerated
    And the payment amount should be autogenerated
    When the user clicks on Blood Issue Save button
    Then the issued blood record should be displayed in the Blood Issue Details.

  @DeleteIssuedBloodRecord
  Scenario: Delete issued blood record
    When the user clicks delete button for issued blood record
    And the user accepts the delete alert
    Then the issued blood record should be deleted successfully

  @IssueBloodEmptyFields
  Scenario: Issue blood with empty mandatory fields
    When the user clicks on Issue Blood button
    Then the Issue Blood popup should be displayed
    When the user clicks on Blood Issue Save button
    Then the following empty mandatory validation messages should be displayed
      | Issue Date field is required      |
      | Patient field is required         |
      | Reference Name field is required  |
      | Bag field is required             |
      | Charge Name field is required     |
      | Charge Category field is required |
      | Hospital Doctor field is required |
      | Payment Amount field is required  |