package actions;

import java.time.Duration;
import java.util.List;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import Utilities.Helper;
import driver.Driver;
import pages.BloodIssuePage;

public class BloodIssueAction {

    Logger logger = LogManager.getLogger(BloodIssueAction.class);

    public void clickbloodissueDetails() {
        logger.info("Navigated to Blood Issue Details Page");
        Helper.waitForElementClickable(BloodIssuePage.bloodIssuedetails);
        Helper.click(BloodIssuePage.bloodIssuedetails);
    }

    public boolean isbloodIssueDetailsPagedisplayed() {
        Helper.waitForVisibility(BloodIssuePage.issueBloodbutton);
        return Helper.isDisplayed(BloodIssuePage.issueBloodbutton);
    }

    public void clickIssueBloodbutton() {
        logger.info("Issue Blood popup is displayed.");
        Helper.jsClick(BloodIssuePage.issueBloodbutton);
    }

    public boolean isIssueBloodPopupDisplayed() {
        Helper.waitForVisibility(BloodIssuePage.saveButton);
        return Helper.isDisplayed(BloodIssuePage.saveButton);
    }

    public void selectpatient(String patientName) {
        Helper.moveToElementAndClick(BloodIssuePage.patientdropdown);
        Helper.type(BloodIssuePage.searchBox, patientName);
        Helper.waitForVisibility(BloodIssuePage.dynamicOption(patientName));
        Helper.click(BloodIssuePage.dynamicOption(patientName));
    }

    public void enterIssueDate(String issueDate) {
        Helper.getElement(BloodIssuePage.issuedate).clear();
        Helper.setDate(BloodIssuePage.issuedate, issueDate);
        Helper.getElement(BloodIssuePage.issuedate).sendKeys(Keys.TAB); 
    }

    public void selectdoctor(String doctor) {
        Helper.moveToElementAndClick(BloodIssuePage.doctorDropdown);
        Helper.type(BloodIssuePage.searchBox, doctor);
        Helper.getElement(BloodIssuePage.searchBox).sendKeys(Keys.ARROW_DOWN);
        Helper.getElement(BloodIssuePage.searchBox).sendKeys(Keys.ENTER);
    }

    public boolean isBloodgroupAutogenerated() {
        String bloodGroup = Helper.getElement(BloodIssuePage.bloodgroupField).getText(); 
        return bloodGroup != null && !bloodGroup.trim().isEmpty();
    }

    public boolean isReferenceNameAutogenerated() {
        String referenceName = Helper.getElement(BloodIssuePage.referenceNamefield).getAttribute("value");
        return !referenceName.isEmpty();
    }

    public void selectBloodbag() {
        Helper.moveToElementAndClick(BloodIssuePage.bloodBagdropdown);
        Helper.waitForVisibility(BloodIssuePage.searchBox);
        Helper.waitForVisibility(BloodIssuePage.firstOption);
        Helper.click(BloodIssuePage.firstOption);
    }

    public void selectChargeCategory(String chargeCategory) {
        Helper.moveToElementAndClick(BloodIssuePage.chargecategorydropdown);
        Helper.waitForVisibility(BloodIssuePage.searchBox);
        Helper.type(BloodIssuePage.searchBox, chargeCategory);
        Helper.waitForVisibility(BloodIssuePage.dynamicOption(chargeCategory));
        Helper.click(BloodIssuePage.dynamicOption(chargeCategory));
    }

    /*public void selectChargename(String chargeName) {
        Helper.moveToElementAndClick(BloodIssuePage.chargenameDropdown);
        Helper.waitForVisibility(BloodIssuePage.searchBox);
        Helper.type(BloodIssuePage.searchBox, chargeName);
        WebDriverWait wait = new WebDriverWait(Driver.getDriver(), Duration.ofSeconds(20));
        wait.until(ExpectedConditions.invisibilityOfElementLocated(BloodIssuePage.loadingText));
        Helper.getElement(BloodIssuePage.searchBox).sendKeys(Keys.ARROW_DOWN);
        Helper.getElement(BloodIssuePage.searchBox).sendKeys(Keys.ENTER);
    }*/
    public void selectChargeName(String charge) {

        Helper.moveToElementAndClick(BloodIssuePage.chargenameDropdown);

        Helper.waitForVisibility(BloodIssuePage.searchBox);

        Helper.type(BloodIssuePage.searchBox, charge);

        Helper.waitForElementsPresent(
                BloodIssuePage.dynamicOption(charge), 20);

        Helper.click(BloodIssuePage.dynamicOption(charge));
    }
    public boolean isPaymentAmountAutogenerated() {
        String amount = Helper.getElement(BloodIssuePage.paymentfield).getAttribute("value");
        return !amount.isEmpty();
    }

    public void clickSavebutton() {
        Helper.click(BloodIssuePage.saveButton);
    }

    public void clickDeleteButton() {
        logger.info("Deleting issued blood record");
        Helper.moveToElement(BloodIssuePage.firstRow);
        Helper.waitForElementClickable(BloodIssuePage.deleteButton);
        Helper.click(BloodIssuePage.deleteButton);
    }

    public void acceptDeleteAlert() {
        Helper.acceptAlert();
    }

    public boolean isRecordDeletedSuccessfully() {
        Helper.waitForVisibility(BloodIssuePage.deleteMessage);
        logger.info("Blood issue record deleted successfully");
        return Helper.isDisplayed(BloodIssuePage.deleteMessage);
    }

    public boolean isIssuedBloodrecorddisplayed() {
        Helper.waitForVisibility(BloodIssuePage.successMessage);
        String message = Helper.getText(BloodIssuePage.successMessage);
        logger.info(message);
        return message.toLowerCase().contains("success");
    }

    public boolean isValidationMessageDisplayed(String message) {
        WebDriverWait wait = new WebDriverWait(Driver.getDriver(), Duration.ofSeconds(10));
        wait.until(ExpectedConditions.presenceOfAllElementsLocatedBy(BloodIssuePage.validationMessage));
        List<WebElement> toasts = Driver.getDriver().findElements(BloodIssuePage.validationMessage); 
        for (WebElement toast : toasts) {
            if (toast.getText().contains(message)) {
                return true;
            }
        }
        return false;
    }
    
}