package stepDefinition;

import java.io.IOException;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.testng.Assert;

import Utilities.Data_Provider;
import actions.BloodIssueAction;
import actions.DonorManagementAction;
import io.cucumber.java.en.Then;
import io.cucumber.java.en.When;

public class BloodIssueStepDefinition {

    BloodIssueAction bloodIssueAction = new BloodIssueAction();
    Logger logger = LogManager.getLogger(DonorManagementAction.class);

    @When("the user clicks on Blood Issue Details")
    public void the_user_clicks_on_blood_issue_details() {
        bloodIssueAction.clickbloodissueDetails();
    }

    @Then("the Blood Issue Details page should be displayed")
    public void the_blood_issue_details_page_should_be_displayed() {
        Assert.assertTrue(bloodIssueAction.isbloodIssueDetailsPagedisplayed());
    }

    @When("the user clicks on Issue Blood button")
    public void the_user_clicks_on_issue_blood_button() {
        bloodIssueAction.clickIssueBloodbutton();
    }

    @Then("the Issue Blood popup should be displayed")
    public void the_issue_blood_popup_should_be_displayed() {
        Assert.assertTrue(bloodIssueAction.isIssueBloodPopupDisplayed());
    }

    @When("the user selects patient {string} and doctor {string}")
    public void the_user_selects_patient_and_doctor(String patientName, String doctor) {
        bloodIssueAction.selectpatient(patientName);
        bloodIssueAction.selectdoctor(doctor);
    }

    @Then("the blood group should be autogenerated")
    public void the_blood_group_should_be_autogenerated() {
        Assert.assertTrue(bloodIssueAction.isBloodgroupAutogenerated());
    }

    @Then("the reference name should be autogenerated")
    public void the_reference_name_should_be_autogenerated() {
        Assert.assertTrue(bloodIssueAction.isReferenceNameAutogenerated()); 
    }

    @Then("the payment amount should be autogenerated")
    public void the_payment_amount_should_be_autogenerated() {
        Assert.assertTrue(bloodIssueAction.isPaymentAmountAutogenerated());
    }

    @When("the user clicks on Blood Issue Save button")
    public void the_user_clicks_on_blood_issue_save_button() {
        bloodIssueAction.clickSavebutton();
    }

    @Then("the issued blood record should be displayed in the Blood Issue Details.")
    public void the_issued_blood_record_should_be_displayed_in_the_blood_issue_details() {
        Assert.assertTrue(bloodIssueAction.isIssuedBloodrecorddisplayed());
    }

    @When("the user clicks delete button for issued blood record")
    public void the_user_clicks_delete_button_for_issued_blood_record() {
        bloodIssueAction.clickDeleteButton();
    }

    @When("the user accepts the delete alert")
    public void the_user_accepts_the_delete_alert() {
        bloodIssueAction.acceptDeleteAlert();
    }

    @Then("the issued blood record should be deleted successfully")
    public void the_issued_blood_record_should_be_deleted_successfully() {
        Assert.assertTrue(bloodIssueAction.isRecordDeletedSuccessfully());
    }

    @Then("the following empty mandatory validation messages should be displayed")
    public void the_following_empty_mandatory_validation_messages_should_be_displayed(
            io.cucumber.datatable.DataTable dataTable) {
        logger.info("Blood issue is unsuccessful.");
        java.util.List<String> expectedMessages = dataTable.asList();
        for (String message : expectedMessages) {
            Assert.assertTrue(bloodIssueAction.isValidationMessageDisplayed(message) );
        }
    }

    @When("the user enters valid blood issue details")
    public void the_user_enters_valid_blood_issue_details() throws IOException {
        String[][] data =Data_Provider.getExcelData("src/test/resources/test_datas/BloodIssueValid.xlsx","validDetails") ;
        String patientName = String.valueOf((int) Double.parseDouble(data[0][0]));
        String doctor         = data[0][1];
        String issueDate      = data[0][2];
        String chargeCategory = data[0][3];
        String chargeName     =data[0][4];

        bloodIssueAction.selectpatient(patientName);
        bloodIssueAction.enterIssueDate(issueDate);
        bloodIssueAction.selectdoctor(doctor);        
        bloodIssueAction.selectBloodbag();
        bloodIssueAction.selectChargeCategory(chargeCategory);
        bloodIssueAction.selectChargeName(chargeName);
    }
}

